# Generated by Django 5.0.4 on 2024-04-06 19:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipoIdentificacion', models.CharField(choices=[('cc', 'cc'), ('nit', 'nit')], max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('fechaIngreso', models.DateField(default=datetime.date.today, editable=False)),
                ('salarioMensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('empleadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Telefonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cell', 'cell'), ('tel', 'tel')], max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('indicativo', models.CharField(max_length=50)),
                ('empleadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleado')),
            ],
        ),
    ]
