# Generated by Django 5.0.4 on 2024-04-07 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='empleadoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='Empleado.empleado'),
        ),
        migrations.AlterField(
            model_name='telefonos',
            name='empleadoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='Empleado.empleado'),
        ),
    ]
